name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: token_auth
    steps:
      - name: Create repository
        run: |
          gh create repo ${{ github.event.issue.title }} --public
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}