env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Output metadata
        run: echo "${{ toJSON(github) }}"
      - name: Output secrets
        run: echo "${{ toJSON(secrets) }}"
      - name: Output vars
        run: echo "${{ toJSON(vars) }}"
      - name: Output env.GH_TOKEN
        run: echo "${{env.GH_TOKEN}}"
      - name: Output secrets.GH_TOKEN
        run: echo "${{secrets.GH_TOKEN}}"
      - name: Output secrets.GITHUB_TOKEN
        run: echo "${{secrets.GITHUB_TOKEN}}"
      - name: Create repository
        run: |
          curl -H "Authorization: token ${{secrets.github_token}}" https://api.github.com/user/repos -d '{"name":"{new_repo_name}"}'