env:
  super_secret: ${{ secrets.TOKEN_ACCESS}}

name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: token_auth
    steps:
      - name: Extract issue template
        uses: imjohnbo/extract-issue-template-fields@v1
        with:
          path: .github/ISSUE_TEMPLATE/[Repository]_angular-template.yml
      - name: Logs Output from extract
        run: |-
          echo $ASSIGNEES $LABELS $TITLE $BODY