env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions: 
      repository-projects: write
    steps:
      - name: Output metadata
        run: echo "${{ toJSON(github) }}"
      - name: Output secrets
        run: echo "${{ toJSON(secrets) }}"
      - name: Output vars
        run: echo "${{ toJSON(vars) }}"
      - name: Create repository
        run: gh repo create some-repo --public