name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: token_auth
    steps:
      - name: Create repository and get link
        id: repository_data
        run: |
          gh repo create "${{ github.event.issue.title }}" --public \
          echo "REPOSITORY_LINK=$("https://github.com/victorfjansen/${{github.event.issue.title}}")" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}

  comment_repository_link:
    needs: create_repository
    runs-on: ubuntu-latest
    permissions: write-all
    environment: token_auth
    steps:
      - name: Comment on Issue
        run: |
          gh issue comment ${{ github.event.issue.html_url }} -b "${{ env.REPOSITORY_LINK }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
  
  close_issue:
    needs: comment_repository_link
    runs-on: ubuntu-latest
    permissions: write-all
    environment: token_auth
    steps:
      - name: Close issue
        run: |
          gh issue close ${{ github.event.issue.html_url }} -c "closed by automation"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
          