env:
  super_secret: ${{ secrets.TOKEN_ACCESS}}

name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: token_auth
    steps:
      - name: test
        run: |
          echo "Issuel Title: ${{ github.event.issue.title }}"
          echo "Issuel Body: ${{ github.event.issue.body }}"
          echo "Issue content: ${{ toJSON(github.event.issue) }}"
