name: create repository
on: 
  issues: 
    types: [opened]
jobs:
  create_repository:
    runs-on: macos-latest
    steps:
      - name: Create repository
        run: gh repo create some-repo --public
      - name: Output metadata
        run: echo "${{ toJSON(github) }}"